development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: default
  pool: 5
  username: root
  password: admin
  socket: /var/run/mysqld/mysqld.sock

staging:
  adapter: mysql2
  host: 
  reconnect: false
  database:
  username: 
  password: 
